project:
  type: website
  output-dir: docs
  preview:
    port: 166
    browser: true
    navigate: true
  render:
    - "*.qmd"
    - "!_omit/"                             # do not build anything in /_omit
#    - "!slides/"                           # do not build anything in /slides
#    - "!data/building"                      # do not build anything here
#    - "!content_"                           # do not build anything here
#    - "!modules/module_starter_page.qmd"
    #- "!modules/01_installing_r_and_rstudio.qmd"
#    - "!modules/" # Note regarding !, if try to render with an ignore, will get ERROR: TypeError: Cannot convert undefined or null to object


website:
  title: "**PSYC166**"
  navbar:
    left:
      - text: "**Home**"
        file: index.qmd
      - text: "**Syllabus**"
        file: syllabus/syllabus.qmd
      #- text: "Textbook"
      #  href: https://psyteachr.github.io/ads-v2
      - text: "**Modules**"
        file: modules/index.qmd                            # all files in dir are referenced and ordered by file number
      - text: "**Project**"
        file: project/index.qmd                            # will reference subdirs

################################################################################
##    Slides may not be able to be set with _ starting name
      - text: "**Slides**"
        menu:
#        - text: Example 1
#          href: slides/sample_quarto_presentation.qmd
        - text: R, RStudio, & R Markdown
          href: slides/01_intro_rstudio_rmarkdown_slides.qmd
        - text: Git and GitHub
          href: slides/02_git_slides.qmd
        - text: Functions, Parameters, and Arguments
          href: slides/03_functions_slides.qmd
        - text: Vectors and Data Frames
          href: slides/04_vectors_and_data_frames_slides.qmd
        - text: Importing and Exporting Data
          href: slides/05_importing_and_exporting_slides.qmd
        - text: Variables, Measures of Cognition
          href: slides/06_variables_cognition_slides.qmd
        - text: 'Manipulating Data: Pivoting'
          href: slides/07_manipulating_data_pivoting_slides.qmd
        - text: 'Manipulating Data: Selecting, Filtering, & Mutating'
          href: slides/07_manipulating_data_selecting_filtering_mutating_slides.qmd
        - text: Cognitive Task Data
          href: slides/08_cognitive_data_slides.qmd
        - text: Grouping and Summarizing Data
          href: slides/09_summarizing_data_slides.qmd
        - text: Summarizing Task Data
          href: slides/10_cognitive_data_summary_slides.qmd
        - text: Visualizing Data
          href: slides/11_visualizing_data_slides.qmd
        - text: Examining Relationships
          href: slides/12_examining_relationships_slides.qmd
        - text: Joining Data
          href: slides/13_joining_data_slides.qmd
        - text: Strings and Factors
          href: slides/14_strings_and_factors_slides.qmd
        - text: Joining Project Data
          href: slides/15_joining_project_data_slides.qmd
        - text: Discussing Models for Cognitive Tasks
          href: slides/16_models_project_slides.qmd
        - text: Linear Models
          href: slides/17_linear_models_slides.qmd
        - text: Exploratory Data Analysis
          href: slides/18_eda_slides.qmd

################################################################################
      #- text: "**Readings**"
      #  href: readings/readings.qmd

################################################################################

      - text: "**HW**"
        # file: homework/index.qmd         # this quarto file is not used - files referenced separately
        menu:
          - text: HW 1
            href: homework/HW01.Rmd
          - text: HW 2
#            href: homework/HW02.Rmd
          - text: HW 3
#            href: homework/HW03.Rmd
          - text: HW 4
#            href: homework/HW04.Rmd
          - text: HW 5
#            href: homework/HW05.Rmd
          - text: HW 6
#            href: homework/HW06.Rmd
          - text: HW 7
#            file: homework/HW07.Rmd
          - text: HW 8
#            href: homework/HW08.Rmd
          - text: HW 9
#            href: homework/HW09.Rmd
          - text: HW 10
      #      href: "https://raw.githubusercontent.com/slicesofdata/fods24/main/homework/HW10.Rmd")

################################################################################
      - text: "**Exercises**"  # Built like Homework
        menu:
          - text: using_git_with_projects_exercise.Rmd
            href: exercises/using_git_with_projects_exercise.Rmd

          - text: functions_exercise.Rmd
            href: exercises/functions_exercise.Rmd

          - text: vectors_and_dataframes_exercise.Rmd
            href: exercises/vectors_and_dataframes_exercise.Rmd

          - text: imorting_and_exporting_exercise.Rmd
            href: exercises/imorting_and_exporting_exercise.Rmd

          - text: pivoting_exercise.Rmd
            href: exercises/pivoting_exercise.Rmd

          - text: transforming_exercise.Rmd
            href: exercises/transforming_exercise.Rmd

          - text: summarizing_exercise.Rmd
            href: exercises/summarizing_exercise.Rmd

          - text: visualizing_exercise.Rmd
            href: exercises/visualizing_exercise.Rmd

          - text: strings_and_factors_exercise.Rmd
            href: exercises/strings_and_factors_exercise.Rmd

          - text: joining_exercise.Rmd
            href: exercises/joining_exercise.Rmd

          - text: linear_models_exercise.Rmd
            href: exercises/linear_models_exercise.Rmd

          - text: eda_exercise.Rmd
            href: exercises/eda_exercise.Rmd

#
################################################################################
      - text: "**Data**"
        # file: data/index.qmd         # this quarto file is not used
        menu:
          - text: cms-top-all-time-2023-swim.xlsx
            href: https://github.com/slicesofdata/dataviz23/raw/main/data/cms-top-all-time-2023-swim.zip
          - text: Fun Tidy Tuesday Data Sets
            href: https://github.com/rfordatascience/tidytuesday
          - text: Defense Casualty Analysis System (DCAS)
            href: https://dcas.dmdc.osd.mil/dcas/app/home
            #href: https://dcas.dmdc.osd.mil/dcas/app/conflictCasualties/vietnam/vietnamSum

################################################################################
      - text: "**Cheatsheets**"
        #file: cheatsheets/index.qmd     # this quarto file is not used
        menu:
          - text: Symbols
            href: cheatsheets_and_tips/symbols.qmd
          - text: RMarkdown
            href: cheatsheets/rmarkdown-2.0.pdf
          - text: 'Data Wrangling with {dplyr} and {tidyr}'
            href: https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
          - text: Quarto (Publish and Share)
            href: https://rstudio.github.io/cheatsheets/html/quarto.html
          - text: 'String Manipulation with {stringr}'
            href: https://rstudio.github.io/cheatsheets/html/strings.html
          - text: 'Reading and Writing Data with {readr}'
            href: https://rstudio.github.io/cheatsheets/html/data-import.html
          - text: Data Science with RWorkflow
            href: cheatsheets/Data_Science_With_R_Workflow.pdf
          - text: More Cheatsheets From RStudio
            href: https://rstudio.github.io/cheatsheets/
          - text: Quarto Cheat Sheet (what Quarto Files Look Like)
            href: https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf
################################################################################
      - text: "**Other Tools**"
        href: resources/tools.qmd


################################################################################
# on the right of the page
    right:
      - icon: github
        href: https://github.com/slicesofdata
        aria-label: GitHub
      - text: Me
        href: https://gabrielcook.xyz

################################################################################
# to add a topic sidebar
  sidebar:
      #style: "floating"
      #collapse-level: 2
      #align: left
      #contents: auto
    - title: "Home"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - syllabus/syllabus.qmd
        - auto: modules
        - auto: project

    - title: "Slides"
      style: "floating"
      collapse-level: 2
      align: left

################################################################################

format:
  html:
    theme: css/styles.scss
    css: [css/nav.css,css/styles.css]
    toc: true
    include-in-header: "css/fontawesome.html"
    #mainfont: arial #Nunito
    fontsize: 1.1rem # 1.2rem
#    linkcolor: "#096980"
#    monofont: courier new

#css: css/styles.scss

editor: source

