---
title: "Homework 02"
author: "yourname"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  #word_document:
  #  toc: yes
  #  number_sections: yes
  html_document:
    toc: no
    number_sections: yes
    code_folding: show #hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**This homework is due by Thursday by 2:30pm.**

For this homework, you will save the `R Markdown` (e.g., `.Rmd`) homework document and save it to your `/fods-exercises/report` project directory. Either rename it or save a copy of this file so that its name has the prefix `2024_Lastname_FirstInitial`. Full name example: `2024_cookg_HW_02.Rmd`. 

*Enter your name in the author YAML code above*   


# **Overview**

The goal of this homework is to make another step toward the team project. You will soon set up a meeting with the liaison, which we want to make efficient and obtain as much positive direction from them as possible. In pursuit of that goal, you should identify potential variables or measures of interest from the CHAMP data set that could be relevant to the project proposed by your liaison. Although the proposal identifies some key measures and cognitive tasks (e.g., go/no-go, symmetry span), other measures are not specified directly and are instead only conceptualized. This component of the project proposal is to involve you in the process of helping identity relevant variables in a way similar to evaluating variables in data scraped from websites or that which is extracted from meta data. The liaisons have also left this open in order to offer you some flexibility to explore the data in a way or ways that are most interesting to you. In order to have a greater hand in the process, your task is to review some contents of the CHAMPS data so that you can propose approaches to the liaison that can be agreed upon as ways to go. 

# **Project Proposal: Identifying Measures/Variables**

In the `/docs` directory for your **team** project, you will find some files related to the CHAMP data set. The focus will be on using data from Wave 1 of the CHAMP data set. Some key files are:

* **1 - CHAMP - Sources of Data.docx:** A file describing the sources of data and data collection methods for the CHAMP data. This file will be relevant for the section of the final report within which you describe the data.

* **2 - CHAMP - Measurement Instruments.docx:** A file outlining the measurement instruments used during the waves of data collection. Information is provided on the number of items in various measures. The measurement scales also contain information on the response options to questions. Sections also include some citations that you may find relevant. Full citations can be found at the end of the file.

* **3 - CHAMP - Wave One Survey - Codebook.docx:** A large file providing clarity about all variables in the data set, including variable names, coded response options, etc. This file will be relevant for helping you pivot data from wide format to long format, for recoding any verbal responses to numeric, for creating factors with levels, for creating ordered factors, etc. This file will also help provide you with clarity about how to clean variables and describe any details associated with preparing data.  

* **7 - CHAMP - Data Dictionary.xlsx:** A spreadsheet containing measures, rationale (related to the grant), and sources for measures in the data set. Details are redundant with other sections but you may find this file helpful with understanding some hypotheses outlined in the original grant but also to consider hypothesis that were not identified (but may be of interest).  

This item will facilitate the initial meeting with your liaison. You will feel more confident in the meeting and you will have better direction by the conclusion of that meeting, leaving fewer loose ends. Based on your understanding of the proposal, your team will delegate sections of the documents to team members to undergo an initial review of the measures and questions in order to identify some measures that are likely relevant to the project proposal.

Although you may identify more than 5, identify at least 5 questions/measures other than the symmetry span task or the go/no-go task. Reflect on those measures and determine their [level of measurement](https://en.wikipedia.org/wiki/Level_of_measurement) as this will help with models as you might remember from your statistics course. Keep in mind that ratio scales can often still be turned into lower-level variables (e.g., categorical/factors) but nominal/categorical variables cannot easily be converted into numeric. The liaison may ask you a question about the measurement scale so having a response can be advantageous. Based on the measures you identify, I can create future class exercises and homework assignments to help you wrangle them.

**Identify 5 Relevant Measures / level of measurement** (e.g., nominal/categorical/factor; numeric but ordinal; numeric and equal-interval or ratio)

1. 
2. 
3. 
4. 
5. 


 


# **Team Work log and Concerns**

Importantly, you want to have a safeguard for accountability. I recommend keeping a shared document that you complete after each weekly team meeting in order to identify tasks that each team member will set out to accomplish by the next weekly meeting. If you do create such a file, please share it with me. That content could be placed here for me to review if you don't share with me. 

## **Weekly Accomplishments for Team**

Please itemize/bullet point your personal accomplishments/tasks completed for your team as discussed/delegated in your team meeting. 



## **Team Issues**

Please itemize/bullet point any issues with team communication, task delegation, lack of follow-through as promised, etc. so that I understand them and look into.






# **Optional**

If your team has time to accomplish this element, do so this week or postpone until next week.

## **Readings**

The project proposal includes readings that the liaison has identified as relevant for understanding the motivation for the project. These papers are in `/refs`. The final report should at very least include these papers as references. In addition to those papers, I have included other papers co-authored by James Pike, a coauthor on the grant for the CHAMP data. These references are supplemental to those identified by the liaison but may prove fruitful to your project as some papers are based on the CHAMP data or use tasks or measurements in the CHAMP data.  

At some point, team members should determine which papers to read and agree how they will  distribute them to team members based on factors the team deems relevant (e.g., background knowledge, courses taken, etc.). Setting a timeline for both reading and discussing their importance in a future meeting is suggested so that there is no ambiguity among the team members about due dates, though I will not personally set a date. If some members have the time to review their share before the first liaison meeting, having that background may also prove useful, though not required.

Once completed, specify the member name and dedicted paper(s) below.

Member name: Citation(s)





Finally, knit an `html` file containing that image file and upload to: https://claremontmckenna.app.box.com/f/026ed41483fb4a739f0ddfc7fbf8fd01


