---
title: "Homework 05"
#author: "yourname"
#date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: false
    number_sections: true
    code_folding: show
  pdf_document:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
R.utils::sourceDirectory(here::here("r", "functions"))
```

**This homework is due by Thursday by 2:30pm.**

For this homework, you will create files in your personal version of the team project (e.g., `<liaison-yourname>` project), commit those files, and push to your GitHub account. Evaluation will be based on a review of your repository status by the due date. Feel free to create your files in your exercises/homework project and then move them to your `<liaison-yourname>` project.

This homework does not involve complicated coding practice but instead involves building your file hierarchy. There are, however, detailed instructions on the names of files and the directories within which to create them in order to eliminate the problem solving on your end about how everything will work together. Once you have your code files created, you can start migrating relevant code that you used to complete in-class exercises and homework assignments that addressed parts of the components.


# **Overview**

Instructions for the homework are in a separate file to keep the homework file short. You can:

- download the instructions for this homework from https://raw.githubusercontent.com/slicesofdata/fods24/main/homework/HW05_instructions.pdf
- or view at https://github.com/slicesofdata/fods24/blob/main/homework/HW05_instructions.pdf


# **Creating your Script Files**

As referenced in a previous class exercise, your script files should contain authorship details, a clear description of the goal of the script and what it does, as well as readable sub-sections that are easy to follow. A [general template file was located here](https://raw.githubusercontent.com/slicesofdata/fods24/main/r/script_template_block.txt). 

In your personal team project `<liaison-yourname>`, create:

**Data Processing**

- layer 4: `/r/<subtask>/<subtask>_long_clean.R`
- layer 3: `/r/<subtask>/<subtask>_wide_to_long.R`
- layer 2: `/r/<subtask>/champ_all_waves_create_<subtask>_subset.R`

**Base Script**

- layer 1: `/r/champ_all_waves_initial_clean.R`

**Note:** Additional files described in the instructions will need to be created as you and your team accomplish those goals. 


# **Editing your Script Files**

Inside each script file, you should:

- load the relevant libraries needed for that script to run, and
- source dependent script file; and
- include code to read in the data produced by the dependent script file; and
- include code to write out data files; and
- aim to provide clear documentation of goal of the code sections so that you and your liaison can understand it


# **Adding, Committing, and Pushing to your GitHub Remote Repo**

After you create each file, add it to Git, commit it with a message, and push to your remote repository. Repeat for all files. 

